# Generated by Django 5.2.1 on 2025-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_soldproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('paint', 'Paint & Finishes'), ('tools', 'Tools'), ('home_appliances', 'Home Appliances'), ('building_materials', 'Building Materials')], max_length=50),
        ),
    ]
