# Generated by Django 5.2.1 on 2025-07-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='buyer_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
