# Generated by Django 5.2.1 on 2025-07-03 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_soldproduct_buyer_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='soldproduct',
            name='buyer_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('individual', 'Individual')], default='individual', max_length=20),
        ),
    ]
